name: CI
on:
  push:
  workflow_dispatch:

jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependency
        run: pip install black flake8 pytest -i https://pypi.tuna.tsinghua.edu.cn/simple

      - name: Check format (black)
        run: black --check calc.py test_calc.py

      - name: Run linter flake8
        run: flake8 calc.py test_calc.py

      - name: Run unit test pytest
        run: pytest test_calc.py

